diff --git a/kernel/trace/Makefile b/kernel/trace/Makefile
index a818cf089b67..ad86965de658 100644
--- a/kernel/trace/Makefile
+++ b/kernel/trace/Makefile
@@ -43,6 +43,8 @@ obj-$(CONFIG_SCHED_TRACER) += trace_sched_wakeup.o
 obj-$(CONFIG_NOP_TRACER) += trace_nop.o
 obj-$(CONFIG_STACK_TRACER) += trace_stack.o
 obj-$(CONFIG_MMIOTRACE) += trace_mmiotrace.o
+obj-$(CONFIG_HWIOTRACE) += trace_hwiotrace.o
+obj-$(CONFIG_HWIOFUZZ) += trace_hwiofuzz.o
 obj-$(CONFIG_FUNCTION_GRAPH_TRACER) += trace_functions_graph.o
 obj-$(CONFIG_TRACE_BRANCH_PROFILING) += trace_branch.o
 obj-$(CONFIG_BLK_DEV_IO_TRACE) += blktrace.o
